// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2.5
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_PUBSUBS_TSTUSB_H_
#define _TAO_IDL_PUBSUBS_TSTUSB_H_


#include "PubSubC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::Chunk>
    : public
        Var_Size_SArg_Traits_T<
            ::Chunk,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::Pub_Sub::Event>
    : public
        Var_Size_SArg_Traits_T<
            ::Pub_Sub::Event,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_PUB_SUB_CONSUMER__SARG_TRAITS_)
#define _PUB_SUB_CONSUMER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::Pub_Sub::Consumer>
    : public
        Object_SArg_Traits_T<
            ::Pub_Sub::Consumer_ptr,
            ::Pub_Sub::Consumer_var,
            ::Pub_Sub::Consumer_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:147

#if !defined (_PUB_SUB_NOTIFIER__SARG_TRAITS_)
#define _PUB_SUB_NOTIFIER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::Pub_Sub::Notifier>
    : public
        Object_SArg_Traits_T<
            ::Pub_Sub::Notifier_ptr,
            ::Pub_Sub::Notifier_var,
            ::Pub_Sub::Notifier_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_Pub_Sub
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:76

  class Consumer;
  typedef Consumer *Consumer_ptr;

  class  Consumer
    : public virtual PortableServer::ServantBase
  {
  protected:
    Consumer (void);
  
  public:
    /// Useful for template programming.
    typedef ::Pub_Sub::Consumer _stub_type;
    typedef ::Pub_Sub::Consumer_ptr _stub_ptr_type;
    typedef ::Pub_Sub::Consumer_var _stub_var_type;

    Consumer (const Consumer& rhs);
    virtual ~Consumer (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::Pub_Sub::Consumer *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual void push (
      const ::Pub_Sub::Event & event_instance) = 0;

    static void push_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual void disconnect (
      const char * reason) = 0;

    static void disconnect_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_sh.cpp:76

  class Notifier;
  typedef Notifier *Notifier_ptr;

  class  Notifier
    : public virtual PortableServer::ServantBase
  {
  protected:
    Notifier (void);
  
  public:
    /// Useful for template programming.
    typedef ::Pub_Sub::Notifier _stub_type;
    typedef ::Pub_Sub::Notifier_ptr _stub_ptr_type;
    typedef ::Pub_Sub::Notifier_var _stub_var_type;

    Notifier (const Notifier& rhs);
    virtual ~Notifier (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::Pub_Sub::Notifier *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual void disconnect (
      const char * reason) = 0;

    static void disconnect_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual void push (
      const ::Pub_Sub::Event & event_instance) = 0;

    static void push_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual void subscribe (
      ::Pub_Sub::Consumer_ptr subscriber,
      const char * filtering_criteria) = 0;

    static void subscribe_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_sh.cpp:39

    virtual void unsubscribe (
      ::Pub_Sub::Consumer_ptr unsubscriber,
      const char * filtering_criteria) = 0;

    static void unsubscribe_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module Pub_Sub

#endif /* ifndef */

