// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2.5
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:1673

#include "Event_CommI.h"

// Implementation skeleton constructor
Event_Comm_Consumer_i::Event_Comm_Consumer_i (void)
{
}

// Implementation skeleton destructor
Event_Comm_Consumer_i::~Event_Comm_Consumer_i (void)
{
}

void Event_Comm_Consumer_i::push (
  const ::Event_Comm::Event & event_instance)
{
  // Add your implementation here
}

void Event_Comm_Consumer_i::disconnect (
  const char * reason)
{
  // Add your implementation here
}

// Implementation skeleton constructor
Event_Comm_Notifier_i::Event_Comm_Notifier_i (void)
{
}

// Implementation skeleton destructor
Event_Comm_Notifier_i::~Event_Comm_Notifier_i (void)
{
}

void Event_Comm_Notifier_i::disconnect (
  const char * reason)
{
  // Add your implementation here
}

void Event_Comm_Notifier_i::push (
  const ::Event_Comm::Event & event_instance)
{
  // Add your implementation here
}

void Event_Comm_Notifier_i::subscribe (
  ::Event_Comm::Consumer_ptr subscriber,
  const char * filtering_criteria)
{
  // Add your implementation here
}

void Event_Comm_Notifier_i::unsubscribe (
  ::Event_Comm::Consumer_ptr unsubscriber,
  const char * filtering_criteria)
{
  // Add your implementation here
}

