// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2.5
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "Event_CommC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/AnyTypeCode/Struct_TypeCode_Static.h"
#include "tao/AnyTypeCode/TypeCode_Struct_Field.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/SystemException.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/AnyTypeCode/Any_Dual_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "Event_CommC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:88

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Event_Comm_Event[] =
      {
        { "tag_", &CORBA::_tc_string },
        { "value_", &CORBA::_tc_any },
        { "object_ref_", &CORBA::_tc_Object }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Event_Comm_Event (
  ::CORBA::tk_struct,
  "IDL:Event_Comm/Event:1.0",
  "Event",
  _tao_fields_Event_Comm_Event,
  3);


namespace Event_Comm
{
  ::CORBA::TypeCode_ptr const _tc_Event =
    &_tao_tc_Event_Comm_Event;
}

// TAO_IDL - Generated from
// be/be_visitor_structure/structure_cs.cpp:59

void
Event_Comm::Event::_tao_any_destructor (
    void *_tao_void_pointer)
{
  Event *_tao_tmp_pointer =
    static_cast<Event *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Event_Comm::Consumer.

Event_Comm::Consumer_ptr
TAO::Objref_Traits<Event_Comm::Consumer>::duplicate (
    Event_Comm::Consumer_ptr p)
{
  return Event_Comm::Consumer::_duplicate (p);
}

void
TAO::Objref_Traits<Event_Comm::Consumer>::release (
    Event_Comm::Consumer_ptr p)
{
  ::CORBA::release (p);
}

Event_Comm::Consumer_ptr
TAO::Objref_Traits<Event_Comm::Consumer>::nil (void)
{
  return Event_Comm::Consumer::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Event_Comm::Consumer>::marshal (
    const Event_Comm::Consumer_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
Event_Comm::Consumer::push (
  const ::Event_Comm::Event & event_instance)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::Event_Comm::Event>::in_arg_val _tao_event_instance (event_instance);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event_instance
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "push",
      4,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
Event_Comm::Consumer::disconnect (
  const char * reason)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_reason (reason);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_reason
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "disconnect",
      10,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);
}

Event_Comm::Consumer::Consumer (void)
{
}

Event_Comm::Consumer::~Consumer (void)
{
}

void
Event_Comm::Consumer::_tao_any_destructor (void *_tao_void_pointer)
{
  Consumer *_tao_tmp_pointer =
    static_cast<Consumer *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Event_Comm::Consumer_ptr
Event_Comm::Consumer::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Consumer>::narrow (
        _tao_objref,
        "IDL:Event_Comm/Consumer:1.0");
}

Event_Comm::Consumer_ptr
Event_Comm::Consumer::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Consumer>::unchecked_narrow (
        _tao_objref);
}

Event_Comm::Consumer_ptr
Event_Comm::Consumer::_nil (void)
{
  return 0;
}

Event_Comm::Consumer_ptr
Event_Comm::Consumer::_duplicate (Consumer_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Event_Comm::Consumer::_tao_release (Consumer_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Event_Comm::Consumer::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:Event_Comm/Consumer:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Event_Comm::Consumer::_interface_repository_id (void) const
{
  return "IDL:Event_Comm/Consumer:1.0";
}

::CORBA::Boolean
Event_Comm::Consumer::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:72

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Event_Comm_Consumer (
    ::CORBA::tk_objref,
    "IDL:Event_Comm/Consumer:1.0",
    "Consumer");
  

namespace Event_Comm
{
  ::CORBA::TypeCode_ptr const _tc_Consumer =
    &_tao_tc_Event_Comm_Consumer;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Event_Comm::Notifier.

Event_Comm::Notifier_ptr
TAO::Objref_Traits<Event_Comm::Notifier>::duplicate (
    Event_Comm::Notifier_ptr p)
{
  return Event_Comm::Notifier::_duplicate (p);
}

void
TAO::Objref_Traits<Event_Comm::Notifier>::release (
    Event_Comm::Notifier_ptr p)
{
  ::CORBA::release (p);
}

Event_Comm::Notifier_ptr
TAO::Objref_Traits<Event_Comm::Notifier>::nil (void)
{
  return Event_Comm::Notifier::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Event_Comm::Notifier>::marshal (
    const Event_Comm::Notifier_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_exception/exception_ctor.cpp:54

Event_Comm::Notifier::CannotSubscribe::CannotSubscribe (
    const char * _tao_reason_)
  : ::CORBA::UserException (
        "IDL:Event_Comm/Notifier/CannotSubscribe:1.0",
        "CannotSubscribe"
      )
{
  this->reason_ = ::CORBA::string_dup (_tao_reason_);
}



// TAO_IDL - Generated from
// be/be_visitor_exception/exception_cs.cpp:101

Event_Comm::Notifier::CannotSubscribe::CannotSubscribe (void)
  : ::CORBA::UserException (
        "IDL:Event_Comm/Notifier/CannotSubscribe:1.0",
        "CannotSubscribe"
      )
{
}

Event_Comm::Notifier::CannotSubscribe::~CannotSubscribe (void)
{
}

Event_Comm::Notifier::CannotSubscribe::CannotSubscribe (const ::Event_Comm::Notifier::CannotSubscribe &_tao_excp)
  : ::CORBA::UserException (
        _tao_excp._rep_id (),
        _tao_excp._name ()
      )
{
  this->reason_ = ::CORBA::string_dup (_tao_excp.reason_.in ());
}

Event_Comm::Notifier::CannotSubscribe&
Event_Comm::Notifier::CannotSubscribe::operator= (const ::Event_Comm::Notifier::CannotSubscribe &_tao_excp)
{
  this->::CORBA::UserException::operator= (_tao_excp);
  this->reason_ = ::CORBA::string_dup (_tao_excp.reason_.in ());
  return *this;
}

void Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor (void *_tao_void_pointer)
{
  CannotSubscribe *_tao_tmp_pointer =
    static_cast<CannotSubscribe *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

Event_Comm::Notifier::CannotSubscribe *
Event_Comm::Notifier::CannotSubscribe::_downcast ( ::CORBA::Exception *_tao_excp)
{
  return dynamic_cast<CannotSubscribe *> (_tao_excp);
}

const Event_Comm::Notifier::CannotSubscribe *
Event_Comm::Notifier::CannotSubscribe::_downcast ( ::CORBA::Exception const *_tao_excp)
{
  return dynamic_cast<const CannotSubscribe *> (_tao_excp);
}

::CORBA::Exception *Event_Comm::Notifier::CannotSubscribe::_alloc (void)
{
  ::CORBA::Exception *retval = 0;
  ACE_NEW_RETURN (retval, ::Event_Comm::Notifier::CannotSubscribe, 0);
  return retval;
}

::CORBA::Exception *
Event_Comm::Notifier::CannotSubscribe::_tao_duplicate (void) const
{
  ::CORBA::Exception *result = 0;
  ACE_NEW_RETURN (
      result,
      ::Event_Comm::Notifier::CannotSubscribe (*this),
      0
    );
  return result;
}

void Event_Comm::Notifier::CannotSubscribe::_raise (void) const
{
  throw *this;
}

void Event_Comm::Notifier::CannotSubscribe::_tao_encode (TAO_OutputCDR &cdr) const
{
  if (!(cdr << *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

void Event_Comm::Notifier::CannotSubscribe::_tao_decode (TAO_InputCDR &cdr)
{
  if (!(cdr >> *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr Event_Comm::Notifier::CannotSubscribe::_tao_type (void) const
{
  return ::Event_Comm::Notifier::_tc_CannotSubscribe;
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:88

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Event_Comm_Notifier_CannotSubscribe[] =
      {
        { "reason_", &CORBA::_tc_string }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Event_Comm_Notifier_CannotSubscribe (
  ::CORBA::tk_except,
  "IDL:Event_Comm/Notifier/CannotSubscribe:1.0",
  "CannotSubscribe",
  _tao_fields_Event_Comm_Notifier_CannotSubscribe,
  1);

::CORBA::TypeCode_ptr const Event_Comm::Notifier::_tc_CannotSubscribe =
  &_tao_tc_Event_Comm_Notifier_CannotSubscribe;

// TAO_IDL - Generated from
// be/be_visitor_exception/exception_ctor.cpp:54

Event_Comm::Notifier::CannotUnsubscribe::CannotUnsubscribe (
    const char * _tao_reason_)
  : ::CORBA::UserException (
        "IDL:Event_Comm/Notifier/CannotUnsubscribe:1.0",
        "CannotUnsubscribe"
      )
{
  this->reason_ = ::CORBA::string_dup (_tao_reason_);
}



// TAO_IDL - Generated from
// be/be_visitor_exception/exception_cs.cpp:101

Event_Comm::Notifier::CannotUnsubscribe::CannotUnsubscribe (void)
  : ::CORBA::UserException (
        "IDL:Event_Comm/Notifier/CannotUnsubscribe:1.0",
        "CannotUnsubscribe"
      )
{
}

Event_Comm::Notifier::CannotUnsubscribe::~CannotUnsubscribe (void)
{
}

Event_Comm::Notifier::CannotUnsubscribe::CannotUnsubscribe (const ::Event_Comm::Notifier::CannotUnsubscribe &_tao_excp)
  : ::CORBA::UserException (
        _tao_excp._rep_id (),
        _tao_excp._name ()
      )
{
  this->reason_ = ::CORBA::string_dup (_tao_excp.reason_.in ());
}

Event_Comm::Notifier::CannotUnsubscribe&
Event_Comm::Notifier::CannotUnsubscribe::operator= (const ::Event_Comm::Notifier::CannotUnsubscribe &_tao_excp)
{
  this->::CORBA::UserException::operator= (_tao_excp);
  this->reason_ = ::CORBA::string_dup (_tao_excp.reason_.in ());
  return *this;
}

void Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor (void *_tao_void_pointer)
{
  CannotUnsubscribe *_tao_tmp_pointer =
    static_cast<CannotUnsubscribe *> (_tao_void_pointer);
  delete _tao_tmp_pointer;
}

Event_Comm::Notifier::CannotUnsubscribe *
Event_Comm::Notifier::CannotUnsubscribe::_downcast ( ::CORBA::Exception *_tao_excp)
{
  return dynamic_cast<CannotUnsubscribe *> (_tao_excp);
}

const Event_Comm::Notifier::CannotUnsubscribe *
Event_Comm::Notifier::CannotUnsubscribe::_downcast ( ::CORBA::Exception const *_tao_excp)
{
  return dynamic_cast<const CannotUnsubscribe *> (_tao_excp);
}

::CORBA::Exception *Event_Comm::Notifier::CannotUnsubscribe::_alloc (void)
{
  ::CORBA::Exception *retval = 0;
  ACE_NEW_RETURN (retval, ::Event_Comm::Notifier::CannotUnsubscribe, 0);
  return retval;
}

::CORBA::Exception *
Event_Comm::Notifier::CannotUnsubscribe::_tao_duplicate (void) const
{
  ::CORBA::Exception *result = 0;
  ACE_NEW_RETURN (
      result,
      ::Event_Comm::Notifier::CannotUnsubscribe (*this),
      0
    );
  return result;
}

void Event_Comm::Notifier::CannotUnsubscribe::_raise (void) const
{
  throw *this;
}

void Event_Comm::Notifier::CannotUnsubscribe::_tao_encode (TAO_OutputCDR &cdr) const
{
  if (!(cdr << *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

void Event_Comm::Notifier::CannotUnsubscribe::_tao_decode (TAO_InputCDR &cdr)
{
  if (!(cdr >> *this))
    {
      throw ::CORBA::MARSHAL ();
    }
}

// TAO extension - the virtual _type method.
::CORBA::TypeCode_ptr Event_Comm::Notifier::CannotUnsubscribe::_tao_type (void) const
{
  return ::Event_Comm::Notifier::_tc_CannotUnsubscribe;
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/struct_typecode.cpp:88

static TAO::TypeCode::Struct_Field<
  char const *,
  ::CORBA::TypeCode_ptr const *> const 
    _tao_fields_Event_Comm_Notifier_CannotUnsubscribe[] =
      {
        { "reason_", &CORBA::_tc_string }
      };
  
static TAO::TypeCode::Struct<
  char const *,
  ::CORBA::TypeCode_ptr const *,
  TAO::TypeCode::Struct_Field<
    char const *,
    ::CORBA::TypeCode_ptr const *> const *,
  TAO::Null_RefCount_Policy>
_tao_tc_Event_Comm_Notifier_CannotUnsubscribe (
  ::CORBA::tk_except,
  "IDL:Event_Comm/Notifier/CannotUnsubscribe:1.0",
  "CannotUnsubscribe",
  _tao_fields_Event_Comm_Notifier_CannotUnsubscribe,
  1);

::CORBA::TypeCode_ptr const Event_Comm::Notifier::_tc_CannotUnsubscribe =
  &_tao_tc_Event_Comm_Notifier_CannotUnsubscribe;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
Event_Comm::Notifier::disconnect (
  const char * reason)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< char *>::in_arg_val _tao_reason (reason);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_reason
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "disconnect",
      10,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
Event_Comm::Notifier::push (
  const ::Event_Comm::Event & event_instance)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::Event_Comm::Event>::in_arg_val _tao_event_instance (event_instance);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_event_instance
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "push",
      4,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
Event_Comm::Notifier::subscribe (
  ::Event_Comm::Consumer_ptr subscriber,
  const char * filtering_criteria)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::Event_Comm::Consumer>::in_arg_val _tao_subscriber (subscriber);
  TAO::Arg_Traits< char *>::in_arg_val _tao_filtering_criteria (filtering_criteria);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_subscriber,
      &_tao_filtering_criteria
    };

  static TAO::Exception_Data
  _tao_Event_Comm_Notifier_subscribe_exceptiondata [] = 
    {
      {
        "IDL:Event_Comm/Notifier/CannotSubscribe:1.0",
        Event_Comm::Notifier::CannotSubscribe::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , Event_Comm::Notifier::_tc_CannotSubscribe
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "subscribe",
      9,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (
      _tao_Event_Comm_Notifier_subscribe_exceptiondata,
      1
    );
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
Event_Comm::Notifier::unsubscribe (
  ::Event_Comm::Consumer_ptr unsubscriber,
  const char * filtering_criteria)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::Event_Comm::Consumer>::in_arg_val _tao_unsubscriber (unsubscriber);
  TAO::Arg_Traits< char *>::in_arg_val _tao_filtering_criteria (filtering_criteria);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_unsubscriber,
      &_tao_filtering_criteria
    };

  static TAO::Exception_Data
  _tao_Event_Comm_Notifier_unsubscribe_exceptiondata [] = 
    {
      {
        "IDL:Event_Comm/Notifier/CannotUnsubscribe:1.0",
        Event_Comm::Notifier::CannotUnsubscribe::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , Event_Comm::Notifier::_tc_CannotUnsubscribe
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "unsubscribe",
      11,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (
      _tao_Event_Comm_Notifier_unsubscribe_exceptiondata,
      1
    );
}

Event_Comm::Notifier::Notifier (void)
{
}

Event_Comm::Notifier::~Notifier (void)
{
}

void
Event_Comm::Notifier::_tao_any_destructor (void *_tao_void_pointer)
{
  Notifier *_tao_tmp_pointer =
    static_cast<Notifier *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Event_Comm::Notifier_ptr
Event_Comm::Notifier::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Notifier>::narrow (
        _tao_objref,
        "IDL:Event_Comm/Notifier:1.0");
}

Event_Comm::Notifier_ptr
Event_Comm::Notifier::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Notifier>::unchecked_narrow (
        _tao_objref);
}

Event_Comm::Notifier_ptr
Event_Comm::Notifier::_nil (void)
{
  return 0;
}

Event_Comm::Notifier_ptr
Event_Comm::Notifier::_duplicate (Notifier_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Event_Comm::Notifier::_tao_release (Notifier_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Event_Comm::Notifier::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:Event_Comm/Notifier:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Event_Comm::Notifier::_interface_repository_id (void) const
{
  return "IDL:Event_Comm/Notifier:1.0";
}

::CORBA::Boolean
Event_Comm::Notifier::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:72

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Event_Comm_Notifier (
    ::CORBA::tk_objref,
    "IDL:Event_Comm/Notifier:1.0",
    "Notifier");
  

namespace Event_Comm
{
  ::CORBA::TypeCode_ptr const _tc_Notifier =
    &_tao_tc_Event_Comm_Notifier;
}

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_cs.cpp:46



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Comm
{
  /// Copying insertion.
  void operator<<= (
      ::CORBA::Any &_tao_any,
      const ::Event_Comm::Event &_tao_elem)
  {
    if (0 == &_tao_elem) // Trying to de-reference NULL object
      _tao_any <<= static_cast< ::Event_Comm::Event *>( 0 ); // Use non-copying insertion of a NULL
    else
      TAO::Any_Dual_Impl_T< ::Event_Comm::Event>::insert_copy (
          _tao_any,
          ::Event_Comm::Event::_tao_any_destructor,
          ::Event_Comm::_tc_Event,
          _tao_elem);
  }

  /// Non-copying insertion.
  void operator<<= (
      ::CORBA::Any &_tao_any, ::
      Event_Comm::Event *_tao_elem)
  {
    TAO::Any_Dual_Impl_T< ::Event_Comm::Event>::insert (
        _tao_any,
        ::Event_Comm::Event::_tao_any_destructor,
        ::Event_Comm::_tc_Event,
        _tao_elem);
  }

  /// Extraction to non-const pointer (deprecated).
  ::CORBA::Boolean operator>>= (
      const ::CORBA::Any &_tao_any,
      ::Event_Comm::Event *&_tao_elem)
  {
    return _tao_any >>= const_cast<
        const ::Event_Comm::Event *&> (
        _tao_elem);
  }

  /// Extraction to const pointer.
  ::CORBA::Boolean operator>>= (
      const ::CORBA::Any &_tao_any,
      const ::Event_Comm::Event *&_tao_elem)
  {
    return
      TAO::Any_Dual_Impl_T< ::Event_Comm::Event>::extract (
          _tao_any,
          ::Event_Comm::Event::_tao_any_destructor,
          ::Event_Comm::_tc_Event,
          _tao_elem
        );
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

/// Copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  const Event_Comm::Event &_tao_elem)
{
  if (0 == &_tao_elem) // Trying to de-reference NULL object
    _tao_any <<= static_cast<Event_Comm::Event *>( 0 ); // Use non-copying insertion of a NULL
  else
    TAO::Any_Dual_Impl_T<Event_Comm::Event>::insert_copy (
      _tao_any,
      Event_Comm::Event::_tao_any_destructor,
      Event_Comm::_tc_Event,
      _tao_elem);
}

/// Non-copying insertion.
void operator<<= (
  ::CORBA::Any &_tao_any,
  Event_Comm::Event *_tao_elem)
{
  TAO::Any_Dual_Impl_T<Event_Comm::Event>::insert (
    _tao_any,
    Event_Comm::Event::_tao_any_destructor,
    Event_Comm::_tc_Event,
    _tao_elem);
}

/// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
  const ::CORBA::Any &_tao_any,
  Event_Comm::Event *&_tao_elem)
{
  return _tao_any >>= const_cast<
      const Event_Comm::Event *&> (
      _tao_elem);
}

/// Extraction to const pointer.
::CORBA::Boolean operator>>= (
  const ::CORBA::Any &_tao_any,
  const Event_Comm::Event *&_tao_elem)
{
  return
    TAO::Any_Dual_Impl_T<Event_Comm::Event>::extract (
      _tao_any,
      Event_Comm::Event::_tao_any_destructor,
      Event_Comm::_tc_Event,
      _tao_elem);
}
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Event_Comm::Consumer>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Comm
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Consumer_ptr _tao_elem)
  {
    Consumer_ptr _tao_objptr =
      Consumer::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Consumer_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Consumer>::insert (
        _tao_any,
        Consumer::_tao_any_destructor,
        _tc_Consumer,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Consumer_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Consumer>::extract (
          _tao_any,
          Consumer::_tao_any_destructor,
          _tc_Consumer,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Comm::Consumer_ptr _tao_elem)
{
  Event_Comm::Consumer_ptr _tao_objptr =
    Event_Comm::Consumer::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Comm::Consumer_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Event_Comm::Consumer>::insert (
      _tao_any,
      Event_Comm::Consumer::_tao_any_destructor,
      Event_Comm::_tc_Consumer,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Event_Comm::Consumer_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Event_Comm::Consumer>::extract (
        _tao_any,
        Event_Comm::Consumer::_tao_any_destructor,
        Event_Comm::_tc_Consumer,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Event_Comm::Notifier>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Comm
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Notifier_ptr _tao_elem)
  {
    Notifier_ptr _tao_objptr =
      Notifier::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Notifier_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Notifier>::insert (
        _tao_any,
        Notifier::_tao_any_destructor,
        _tc_Notifier,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Notifier_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Notifier>::extract (
          _tao_any,
          Notifier::_tao_any_destructor,
          _tc_Notifier,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Comm::Notifier_ptr _tao_elem)
{
  Event_Comm::Notifier_ptr _tao_objptr =
    Event_Comm::Notifier::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Comm::Notifier_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Event_Comm::Notifier>::insert (
      _tao_any,
      Event_Comm::Notifier::_tao_any_destructor,
      Event_Comm::_tc_Notifier,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Event_Comm::Notifier_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Event_Comm::Notifier>::extract (
        _tao_any,
        Event_Comm::Notifier::_tao_any_destructor,
        Event_Comm::_tc_Notifier,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_exception/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Dual_Impl_T<Event_Comm::Notifier::CannotSubscribe>::demarshal_value (TAO_InputCDR & cdr)
  {
    ::CORBA::String_var id;

    if (!(cdr >> id.out ()))
      {
        return false;
      }
    
    try
      {
        this->value_->_tao_decode (cdr);
      }
    catch (const ::CORBA::Exception &)
      {
        return false;
      }

    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Comm
{
  

  // Copying insertion.
  void operator<<= (
      ::CORBA::Any &_tao_any,
      const ::Event_Comm::Notifier::CannotSubscribe &_tao_elem)
  {
    TAO::Any_Dual_Impl_T< ::Event_Comm::Notifier::CannotSubscribe>::insert_copy (
        _tao_any,
        ::Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor,
        ::Event_Comm::Notifier::_tc_CannotSubscribe,
        _tao_elem);
  }

  // Non-copying insertion.
  void operator<<= (
      ::CORBA::Any &_tao_any,
      ::Event_Comm::Notifier::CannotSubscribe *_tao_elem)
  {
    TAO::Any_Dual_Impl_T< ::Event_Comm::Notifier::CannotSubscribe>::insert (
        _tao_any,
        ::Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor,
        ::Event_Comm::Notifier::_tc_CannotSubscribe,
        _tao_elem);
  }

  // Extraction to non-const pointer (deprecated).
  ::CORBA::Boolean operator>>= (
      const ::CORBA::Any &_tao_any,
      ::Event_Comm::Notifier::CannotSubscribe *&_tao_elem)
  {
    return _tao_any >>= const_cast<
        const ::Event_Comm::Notifier::CannotSubscribe *&> (
        _tao_elem);
  }

  // Extraction to const pointer.
  ::CORBA::Boolean operator>>= (
      const ::CORBA::Any &_tao_any,
      const ::Event_Comm::Notifier::CannotSubscribe *&_tao_elem)
  {
    return
      TAO::Any_Dual_Impl_T< ::Event_Comm::Notifier::CannotSubscribe>::extract (
          _tao_any,
          ::Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor,
          ::Event_Comm::Notifier::_tc_CannotSubscribe,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const Event_Comm::Notifier::CannotSubscribe &_tao_elem)
{
  TAO::Any_Dual_Impl_T<Event_Comm::Notifier::CannotSubscribe>::insert_copy (
      _tao_any,
      Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor,
      Event_Comm::Notifier::_tc_CannotSubscribe,
      _tao_elem
    );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Comm::Notifier::CannotSubscribe *_tao_elem)
{
  TAO::Any_Dual_Impl_T<Event_Comm::Notifier::CannotSubscribe>::insert (
      _tao_any,
      Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor,
      Event_Comm::Notifier::_tc_CannotSubscribe,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    Event_Comm::Notifier::CannotSubscribe *&_tao_elem)
{
  return _tao_any >>= const_cast<
      const Event_Comm::Notifier::CannotSubscribe *&> (
      _tao_elem);
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const Event_Comm::Notifier::CannotSubscribe *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<Event_Comm::Notifier::CannotSubscribe>::extract (
        _tao_any,
        Event_Comm::Notifier::CannotSubscribe::_tao_any_destructor,
        Event_Comm::Notifier::_tc_CannotSubscribe,
        _tao_elem);
}
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_exception/any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Dual_Impl_T<Event_Comm::Notifier::CannotUnsubscribe>::demarshal_value (TAO_InputCDR & cdr)
  {
    ::CORBA::String_var id;

    if (!(cdr >> id.out ()))
      {
        return false;
      }
    
    try
      {
        this->value_->_tao_decode (cdr);
      }
    catch (const ::CORBA::Exception &)
      {
        return false;
      }

    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Event_Comm
{
  

  // Copying insertion.
  void operator<<= (
      ::CORBA::Any &_tao_any,
      const ::Event_Comm::Notifier::CannotUnsubscribe &_tao_elem)
  {
    TAO::Any_Dual_Impl_T< ::Event_Comm::Notifier::CannotUnsubscribe>::insert_copy (
        _tao_any,
        ::Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor,
        ::Event_Comm::Notifier::_tc_CannotUnsubscribe,
        _tao_elem);
  }

  // Non-copying insertion.
  void operator<<= (
      ::CORBA::Any &_tao_any,
      ::Event_Comm::Notifier::CannotUnsubscribe *_tao_elem)
  {
    TAO::Any_Dual_Impl_T< ::Event_Comm::Notifier::CannotUnsubscribe>::insert (
        _tao_any,
        ::Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor,
        ::Event_Comm::Notifier::_tc_CannotUnsubscribe,
        _tao_elem);
  }

  // Extraction to non-const pointer (deprecated).
  ::CORBA::Boolean operator>>= (
      const ::CORBA::Any &_tao_any,
      ::Event_Comm::Notifier::CannotUnsubscribe *&_tao_elem)
  {
    return _tao_any >>= const_cast<
        const ::Event_Comm::Notifier::CannotUnsubscribe *&> (
        _tao_elem);
  }

  // Extraction to const pointer.
  ::CORBA::Boolean operator>>= (
      const ::CORBA::Any &_tao_any,
      const ::Event_Comm::Notifier::CannotUnsubscribe *&_tao_elem)
  {
    return
      TAO::Any_Dual_Impl_T< ::Event_Comm::Notifier::CannotUnsubscribe>::extract (
          _tao_any,
          ::Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor,
          ::Event_Comm::Notifier::_tc_CannotUnsubscribe,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// Copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    const Event_Comm::Notifier::CannotUnsubscribe &_tao_elem)
{
  TAO::Any_Dual_Impl_T<Event_Comm::Notifier::CannotUnsubscribe>::insert_copy (
      _tao_any,
      Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor,
      Event_Comm::Notifier::_tc_CannotUnsubscribe,
      _tao_elem
    );
}

// Non-copying insertion.
void operator<<= (
    ::CORBA::Any &_tao_any,
    Event_Comm::Notifier::CannotUnsubscribe *_tao_elem)
{
  TAO::Any_Dual_Impl_T<Event_Comm::Notifier::CannotUnsubscribe>::insert (
      _tao_any,
      Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor,
      Event_Comm::Notifier::_tc_CannotUnsubscribe,
      _tao_elem
    );
}

// Extraction to non-const pointer (deprecated).
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    Event_Comm::Notifier::CannotUnsubscribe *&_tao_elem)
{
  return _tao_any >>= const_cast<
      const Event_Comm::Notifier::CannotUnsubscribe *&> (
      _tao_elem);
}

// Extraction to const pointer.
::CORBA::Boolean operator>>= (
    const ::CORBA::Any &_tao_any,
    const Event_Comm::Notifier::CannotUnsubscribe *&_tao_elem
  )
{
  return
    TAO::Any_Dual_Impl_T<Event_Comm::Notifier::CannotUnsubscribe>::extract (
        _tao_any,
        Event_Comm::Notifier::CannotUnsubscribe::_tao_any_destructor,
        Event_Comm::Notifier::_tc_CannotUnsubscribe,
        _tao_elem);
}
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Comm::Event &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.tag_.in ()) &&
    (strm << _tao_aggregate.value_) &&
    (strm << _tao_aggregate.object_ref_.in ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Comm::Event &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.tag_.out ()) &&
    (strm >> _tao_aggregate.value_) &&
    (strm >> _tao_aggregate.object_ref_.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Comm::Consumer_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Comm::Consumer_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Event_Comm::Consumer RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_exception/cdr_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Comm::Notifier::CannotSubscribe &_tao_aggregate
  )
{
  // First marshal the repository ID.
  if (strm << _tao_aggregate._rep_id ())
    {
      // Now marshal the members (if any).
      return (
        (strm << _tao_aggregate.reason_.in ())
       );
    }
  else
    {
      return false;
    }
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Comm::Notifier::CannotSubscribe &_tao_aggregate
  )
{
  // Demarshal the members.
  return (
    (strm >> _tao_aggregate.reason_.out ())
  );
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_exception/cdr_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Comm::Notifier::CannotUnsubscribe &_tao_aggregate
  )
{
  // First marshal the repository ID.
  if (strm << _tao_aggregate._rep_id ())
    {
      // Now marshal the members (if any).
      return (
        (strm << _tao_aggregate.reason_.in ())
       );
    }
  else
    {
      return false;
    }
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Comm::Notifier::CannotUnsubscribe &_tao_aggregate
  )
{
  // Demarshal the members.
  return (
    (strm >> _tao_aggregate.reason_.out ())
  );
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Event_Comm::Notifier_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Event_Comm::Notifier_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Event_Comm::Notifier RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



