// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2.5
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:1616

#ifndef PUBSUBI_5GPUP2_H_
#define PUBSUBI_5GPUP2_H_

#include "PubSubS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  Pub_Sub_Consumer_i
  : public virtual POA_Pub_Sub::Consumer
{
public:
  // Constructor
  Pub_Sub_Consumer_i (void);

  // Destructor
  virtual ~Pub_Sub_Consumer_i (void);

  virtual
  void push (
    const ::Pub_Sub::Event & event_instance);

  virtual
  void disconnect (
    const char * reason);
};

class  Pub_Sub_Notifier_i
  : public virtual POA_Pub_Sub::Notifier
{
public:
  // Constructor
  Pub_Sub_Notifier_i (void);

  // Destructor
  virtual ~Pub_Sub_Notifier_i (void);

  virtual
  void disconnect (
    const char * reason);

  virtual
  void push (
    const ::Pub_Sub::Event & event_instance);

  virtual
  void subscribe (
    ::Pub_Sub::Consumer_ptr subscriber,
    const char * filtering_criteria);

  virtual
  void unsubscribe (
    ::Pub_Sub::Consumer_ptr unsubscriber,
    const char * filtering_criteria);
};


#endif /* PUBSUBI_H_  */
